import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VisualEditing from "@/components/VisualEditing";
import { draftMode } from "next/headers";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          {draftMode().isEnabled && <VisualEditing />}
          {<SpeedInsights />}
        </Providers>
      </body>
    </html>
  );
}
