import type { Metadata } from "next";
import { Inter } from "next/font/google";
import VisualEditing from "@/components/VisualEditing";
import { draftMode } from "next/headers";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Providers from "./providers";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Providers>
            <Header />
            {children}
            {draftMode().isEnabled && <VisualEditing />}
            {<SpeedInsights />}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
